### ISSUE TITLE
eureka info 띄우기 위한 설정파일 수정

### ISSUE THREAD

**Issue by nonalias** [42Meet/reservation-service#58]
actuator/info

![image](https://user-images.githubusercontent.com/43032377/123100683-48ee4d00-d46e-11eb-8dce-ede5077301b3.png)
![image](https://user-images.githubusercontent.com/43032377/123100706-4c81d400-d46e-11eb-9674-1f05194af0c9.png)

eureka는 등록된 service의 정보를 볼 수 있는 페이지를 제공한다.

그 링크는 `actuator/info` 인데, 
설정을 해주어야 볼 수 있다.

### build.gradle
`    implementation 'org.springframework.boot:spring-boot-starter-actuator'`
추가해주자.

### application.yml
```
management:
  endpoint:
  endpoints:
    web:
      exposure:
        include: info, health
```

추가하면 성공적으로 접속할 수 있다.
![image](https://user-images.githubusercontent.com/43032377/123101015-95398d00-d46e-11eb-99d1-b585872f86ba.png)
