### ISSUE TITLE
docker-compose network bridge 맞추기

### ISSUE THREAD

**Issue by nonalias** [42Meet/reservation-service#85]
## 기본적으로, docker-compose 로 생성한 container와 docker run으로 생성한 container는 대역대가 다르다.
(참고: https://joont92.github.io/docker/network-%EA%B5%AC%EC%A1%B0/)

### 아래 코드를 docker-compose.yml에 주면 네트워크 대역대를 통일시킬 수 있다.
* 참고로, 42meet는 재민님이 만든 network bridge이다.
* member-service와 네트워크 통신을 하기 위해 대역을 맞춘 것이다.
```
networks:
  default:
    external:
      name: 42meet
```
